use crate::error::DomainResult;
use crate::types::{
    CreateDeviceInputWithId, Device, GetDeviceInput, ListDevicesInput, StoreEnvelopesInput,
};
use async_trait::async_trait;

/// Repository trait for device storage operations
/// Infrastructure layer (e.g., ponix-postgres) implements this trait
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait DeviceRepository: Send + Sync {
    /// Create a new device (device_id is already generated by domain service)
    async fn create_device(&self, input: CreateDeviceInputWithId) -> DomainResult<Device>;

    /// Get a device by ID
    async fn get_device(&self, input: GetDeviceInput) -> DomainResult<Option<Device>>;

    /// List all devices for an organization
    async fn list_devices(&self, input: ListDevicesInput) -> DomainResult<Vec<Device>>;
}

/// Repository trait for processed envelope storage operations
/// Infrastructure layer (e.g., ponix-clickhouse) implements this trait
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait ProcessedEnvelopeRepository: Send + Sync {
    /// Store a batch of processed envelopes
    /// Implementations should handle chunking if needed for large batches
    /// Failure handling: entire batch fails atomically (all-or-nothing)
    async fn store_batch(&self, input: StoreEnvelopesInput) -> DomainResult<()>;
}

/// Trait for publishing processed envelopes to message broker
///
/// Implementations should:
/// - Serialize envelope to appropriate format (protobuf)
/// - Publish to message broker (NATS JetStream)
/// - Return error if publish fails
#[cfg_attr(test, mockall::automock)]
#[async_trait]
pub trait ProcessedEnvelopeProducer: Send + Sync {
    /// Publish a single processed envelope
    ///
    /// # Arguments
    /// * `envelope` - ProcessedEnvelope to publish
    ///
    /// # Returns
    /// () on success, DomainError on failure
    async fn publish(&self, envelope: &crate::types::ProcessedEnvelope) -> DomainResult<()>;
}
