use crate::domain::data_stream_definition::PayloadContract;
use crate::domain::result::DomainResult;
use async_trait::async_trait;
use chrono::{DateTime, Utc};
use garde::Validate;

/// Domain representation of a DataStream
/// Simple String types for now - can evolve to newtypes later
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DataStream {
    pub data_stream_id: String,
    pub organization_id: String,
    pub workspace_id: String,
    pub definition_id: String,
    pub gateway_id: String,
    pub name: String,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
}

/// DataStream with its associated definition data (joined query result)
/// Used when we need both data stream info and the backing definition
#[derive(Debug, Clone, PartialEq, Eq, Validate)]
pub struct DataStreamWithDefinition {
    #[garde(skip)]
    pub data_stream_id: String,
    #[garde(skip)]
    pub organization_id: String,
    #[garde(skip)]
    pub workspace_id: String,
    #[garde(skip)]
    pub definition_id: String,
    #[garde(skip)]
    pub gateway_id: String,
    #[garde(skip)]
    pub definition_name: String,
    #[garde(skip)]
    pub name: String,
    #[garde(length(min = 1))]
    pub contracts: Vec<PayloadContract>,
    #[garde(skip)]
    pub created_at: Option<DateTime<Utc>>,
    #[garde(skip)]
    pub updated_at: Option<DateTime<Utc>>,
}

/// Repository input with generated ID (domain service -> repository)
/// Includes the data_stream_id generated by the domain service
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateDataStreamRepoInput {
    pub data_stream_id: String,
    pub organization_id: String,
    pub workspace_id: String,
    pub definition_id: String,
    pub gateway_id: String,
    pub name: String,
}

/// Repository input for retrieving a data stream
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GetDataStreamRepoInput {
    pub data_stream_id: String,
    pub organization_id: String,
    pub workspace_id: String,
}

/// Repository input for listing data streams by workspace
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ListDataStreamsRepoInput {
    pub organization_id: String,
    pub workspace_id: String,
}

/// Repository input for getting a data stream with its definition (joined query)
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GetDataStreamWithDefinitionRepoInput {
    pub data_stream_id: String,
    pub organization_id: String,
}

/// Repository input for listing data streams by gateway
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ListDataStreamsByGatewayRepoInput {
    pub organization_id: String,
    pub gateway_id: String,
}

/// Repository trait for data stream storage operations
/// Infrastructure layer (e.g., ponix-postgres) implements this trait
#[cfg_attr(any(test, feature = "testing"), mockall::automock)]
#[async_trait]
pub trait DataStreamRepository: Send + Sync {
    /// Create a new data stream (data_stream_id is already generated by domain service)
    async fn create_data_stream(
        &self,
        input: CreateDataStreamRepoInput,
    ) -> DomainResult<DataStream>;

    /// Get a data stream by ID
    async fn get_data_stream(
        &self,
        input: GetDataStreamRepoInput,
    ) -> DomainResult<Option<DataStream>>;

    /// List all data streams for a workspace
    async fn list_data_streams(
        &self,
        input: ListDataStreamsRepoInput,
    ) -> DomainResult<Vec<DataStream>>;

    /// Get a data stream with its definition data in a single query (JOIN)
    /// Returns data stream info plus definition's protocol and contracts
    async fn get_data_stream_with_definition(
        &self,
        input: GetDataStreamWithDefinitionRepoInput,
    ) -> DomainResult<Option<DataStreamWithDefinition>>;

    /// List all data streams for a gateway
    async fn list_data_streams_by_gateway(
        &self,
        input: ListDataStreamsByGatewayRepoInput,
    ) -> DomainResult<Vec<DataStream>>;
}
