use crate::domain::end_device_definition::PayloadContract;
use crate::domain::result::DomainResult;
use async_trait::async_trait;
use chrono::{DateTime, Utc};
use garde::Validate;

/// Domain representation of an EndDevice
/// Simple String types for now - can evolve to newtypes later
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EndDevice {
    pub end_device_id: String,
    pub organization_id: String,
    pub definition_id: String,
    pub gateway_id: String,
    pub name: String,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
}

/// EndDevice with its associated definition data (joined query result)
/// Used when we need both end device info and the backing definition
#[derive(Debug, Clone, PartialEq, Eq, Validate)]
pub struct EndDeviceWithDefinition {
    #[garde(skip)]
    pub end_device_id: String,
    #[garde(skip)]
    pub organization_id: String,
    #[garde(skip)]
    pub definition_id: String,
    #[garde(skip)]
    pub gateway_id: String,
    #[garde(skip)]
    pub definition_name: String,
    #[garde(skip)]
    pub name: String,
    #[garde(length(min = 1))]
    pub contracts: Vec<PayloadContract>,
    #[garde(skip)]
    pub created_at: Option<DateTime<Utc>>,
    #[garde(skip)]
    pub updated_at: Option<DateTime<Utc>>,
}

/// Repository input with generated ID (domain service -> repository)
/// Includes the end_device_id generated by the domain service
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateEndDeviceRepoInput {
    pub end_device_id: String,
    pub organization_id: String,
    pub definition_id: String,
    pub gateway_id: String,
    pub name: String,
}

/// Repository input for retrieving an end device
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GetEndDeviceRepoInput {
    pub end_device_id: String,
    pub organization_id: String,
}

/// Repository input for listing end devices by organization
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ListEndDevicesRepoInput {
    pub organization_id: String,
}

/// Repository input for getting an end device with its definition (joined query)
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GetEndDeviceWithDefinitionRepoInput {
    pub end_device_id: String,
    pub organization_id: String,
}

/// Repository input for listing end devices by gateway
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ListEndDevicesByGatewayRepoInput {
    pub organization_id: String,
    pub gateway_id: String,
}

/// Repository trait for end device storage operations
/// Infrastructure layer (e.g., ponix-postgres) implements this trait
#[cfg_attr(any(test, feature = "testing"), mockall::automock)]
#[async_trait]
pub trait EndDeviceRepository: Send + Sync {
    /// Create a new end device (end_device_id is already generated by domain service)
    async fn create_end_device(&self, input: CreateEndDeviceRepoInput) -> DomainResult<EndDevice>;

    /// Get an end device by ID
    async fn get_end_device(&self, input: GetEndDeviceRepoInput)
        -> DomainResult<Option<EndDevice>>;

    /// List all end devices for an organization
    async fn list_end_devices(
        &self,
        input: ListEndDevicesRepoInput,
    ) -> DomainResult<Vec<EndDevice>>;

    /// Get an end device with its definition data in a single query (JOIN)
    /// Returns end device info plus definition's protocol and contracts
    async fn get_end_device_with_definition(
        &self,
        input: GetEndDeviceWithDefinitionRepoInput,
    ) -> DomainResult<Option<EndDeviceWithDefinition>>;

    /// List all end devices for a gateway
    async fn list_end_devices_by_gateway(
        &self,
        input: ListEndDevicesByGatewayRepoInput,
    ) -> DomainResult<Vec<EndDevice>>;
}
