use crate::domain::result::DomainResult;
use async_trait::async_trait;
use chrono::{DateTime, Utc};
use garde::Validate;

/// Domain representation of a Device
/// Simple String types for now - can evolve to newtypes later
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Device {
    pub device_id: String,
    pub organization_id: String,
    pub workspace_id: String,
    pub definition_id: String,
    pub gateway_id: String,
    pub name: String,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
}

/// Device with its associated definition data (joined query result)
/// Used when we need both device info and the backing definition
#[derive(Debug, Clone, PartialEq, Eq, Validate)]
pub struct DeviceWithDefinition {
    #[garde(skip)]
    pub device_id: String,
    #[garde(skip)]
    pub organization_id: String,
    #[garde(skip)]
    pub workspace_id: String,
    #[garde(skip)]
    pub definition_id: String,
    #[garde(skip)]
    pub gateway_id: String,
    #[garde(skip)]
    pub definition_name: String,
    #[garde(skip)]
    pub name: String,
    #[garde(length(min = 1))]
    pub payload_conversion: String,
    #[garde(length(min = 1))]
    pub json_schema: String,
    #[garde(skip)]
    pub created_at: Option<DateTime<Utc>>,
    #[garde(skip)]
    pub updated_at: Option<DateTime<Utc>>,
}

/// Repository input with generated ID (domain service -> repository)
/// Includes the device_id generated by the domain service
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateDeviceRepoInput {
    pub device_id: String,
    pub organization_id: String,
    pub workspace_id: String,
    pub definition_id: String,
    pub gateway_id: String,
    pub name: String,
}

/// Repository input for retrieving a device
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GetDeviceRepoInput {
    pub device_id: String,
    pub organization_id: String,
    pub workspace_id: String,
}

/// Repository input for listing devices by workspace
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ListDevicesRepoInput {
    pub organization_id: String,
    pub workspace_id: String,
}

/// Repository input for getting a device with its definition (joined query)
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GetDeviceWithDefinitionRepoInput {
    pub device_id: String,
    pub organization_id: String,
}

/// Repository input for listing devices by gateway
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ListDevicesByGatewayRepoInput {
    pub organization_id: String,
    pub gateway_id: String,
}

/// Repository trait for device storage operations
/// Infrastructure layer (e.g., ponix-postgres) implements this trait
#[cfg_attr(any(test, feature = "testing"), mockall::automock)]
#[async_trait]
pub trait DeviceRepository: Send + Sync {
    /// Create a new device (device_id is already generated by domain service)
    async fn create_device(&self, input: CreateDeviceRepoInput) -> DomainResult<Device>;

    /// Get a device by ID
    async fn get_device(&self, input: GetDeviceRepoInput) -> DomainResult<Option<Device>>;

    /// List all devices for a workspace
    async fn list_devices(&self, input: ListDevicesRepoInput) -> DomainResult<Vec<Device>>;

    /// Get a device with its definition data in a single query (JOIN)
    /// Returns device info plus definition's payload_conversion and json_schema
    async fn get_device_with_definition(
        &self,
        input: GetDeviceWithDefinitionRepoInput,
    ) -> DomainResult<Option<DeviceWithDefinition>>;

    /// List all devices for a gateway
    async fn list_devices_by_gateway(
        &self,
        input: ListDevicesByGatewayRepoInput,
    ) -> DomainResult<Vec<Device>>;
}
