use crate::domain::result::DomainResult;
use async_trait::async_trait;
use chrono::{DateTime, Utc};

/// Organization domain entity
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Organization {
    pub id: String,
    pub name: String,
    pub deleted_at: Option<DateTime<Utc>>,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
}

/// Repository input for creating an organization with generated ID
/// user_id is mandatory - needed for creating user_organizations junction table entry
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateOrganizationRepoInputWithId {
    pub id: String,
    pub name: String,
    pub user_id: String, // The user creating this organization (mandatory)
}

/// Repository input for getting an organization by ID
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GetOrganizationRepoInput {
    pub organization_id: String,
}

/// Repository input for updating an organization
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UpdateOrganizationRepoInput {
    pub organization_id: String,
    pub name: String,
}

/// Repository input for deleting an organization
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeleteOrganizationRepoInput {
    pub organization_id: String,
}

/// Repository input for listing organizations
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ListOrganizationsRepoInput {}

/// Repository input for getting organizations by user ID
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GetUserOrganizationsRepoInput {
    pub user_id: String,
}

/// Repository trait for organization storage operations
/// Infrastructure layer (e.g., ponix-postgres) implements this trait
#[cfg_attr(any(test, feature = "testing"), mockall::automock)]
#[async_trait]
pub trait OrganizationRepository: Send + Sync {
    /// Create a new organization (id is already generated by domain service)
    async fn create_organization(
        &self,
        input: CreateOrganizationRepoInputWithId,
    ) -> DomainResult<Organization>;

    /// Get an organization by ID (excludes soft deleted)
    async fn get_organization(
        &self,
        input: GetOrganizationRepoInput,
    ) -> DomainResult<Option<Organization>>;

    /// Update an organization
    async fn update_organization(
        &self,
        input: UpdateOrganizationRepoInput,
    ) -> DomainResult<Organization>;

    /// Soft delete an organization
    async fn delete_organization(&self, input: DeleteOrganizationRepoInput) -> DomainResult<()>;

    /// List all active organizations (excludes soft deleted)
    async fn list_organizations(
        &self,
        input: ListOrganizationsRepoInput,
    ) -> DomainResult<Vec<Organization>>;

    /// Get organizations that a user belongs to (excludes soft deleted)
    async fn get_organizations_by_user_id(
        &self,
        input: GetUserOrganizationsRepoInput,
    ) -> DomainResult<Vec<Organization>>;
}
