use crate::domain::result::DomainResult;
use async_trait::async_trait;
use chrono::{DateTime, Utc};

/// Organization domain entity
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Organization {
    pub id: String,
    pub name: String,
    pub deleted_at: Option<DateTime<Utc>>,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
}

/// External input for creating an organization (no ID)
/// user_id is mandatory - organizations must always be created by a user
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateOrganizationInput {
    pub name: String,
    pub user_id: String, // The user creating this organization (mandatory)
}

/// Internal input with generated ID
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateOrganizationInputWithId {
    pub id: String,
    pub name: String,
    pub user_id: String, // The user creating this organization (mandatory)
}

/// Input for getting an organization by ID
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GetOrganizationInput {
    pub organization_id: String,
}

/// Input for updating an organization
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UpdateOrganizationInput {
    pub organization_id: String,
    pub name: String,
}

/// Input for deleting an organization
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeleteOrganizationInput {
    pub organization_id: String,
}

/// Input for listing organizations
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ListOrganizationsInput {}

/// Repository trait for organization storage operations
/// Infrastructure layer (e.g., ponix-postgres) implements this trait
#[cfg_attr(any(test, feature = "testing"), mockall::automock)]
#[async_trait]
pub trait OrganizationRepository: Send + Sync {
    /// Create a new organization (id is already generated by domain service)
    async fn create_organization(
        &self,
        input: CreateOrganizationInputWithId,
    ) -> DomainResult<Organization>;

    /// Get an organization by ID (excludes soft deleted)
    async fn get_organization(
        &self,
        input: GetOrganizationInput,
    ) -> DomainResult<Option<Organization>>;

    /// Update an organization
    async fn update_organization(
        &self,
        input: UpdateOrganizationInput,
    ) -> DomainResult<Organization>;

    /// Soft delete an organization
    async fn delete_organization(&self, input: DeleteOrganizationInput) -> DomainResult<()>;

    /// List all active organizations (excludes soft deleted)
    async fn list_organizations(
        &self,
        input: ListOrganizationsInput,
    ) -> DomainResult<Vec<Organization>>;
}
