use crate::domain::result::DomainResult;
use async_trait::async_trait;
use chrono::{DateTime, Utc};

/// Workspace domain entity
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Workspace {
    pub id: String,
    pub name: String,
    pub organization_id: String,
    pub deleted_at: Option<DateTime<Utc>>,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
}

/// Repository input for creating a workspace with generated ID
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateWorkspaceRepoInputWithId {
    pub id: String,
    pub name: String,
    pub organization_id: String,
}

/// Repository input for getting a workspace by ID
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GetWorkspaceRepoInput {
    pub workspace_id: String,
    pub organization_id: String,
}

/// Repository input for updating a workspace
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UpdateWorkspaceRepoInput {
    pub workspace_id: String,
    pub organization_id: String,
    pub name: String,
}

/// Repository input for deleting a workspace
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeleteWorkspaceRepoInput {
    pub workspace_id: String,
    pub organization_id: String,
}

/// Repository input for listing workspaces by organization
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ListWorkspacesRepoInput {
    pub organization_id: String,
}

/// Repository trait for workspace storage operations
#[cfg_attr(any(test, feature = "testing"), mockall::automock)]
#[async_trait]
pub trait WorkspaceRepository: Send + Sync {
    /// Create a new workspace (id is already generated by domain service)
    async fn create_workspace(
        &self,
        input: CreateWorkspaceRepoInputWithId,
    ) -> DomainResult<Workspace>;

    /// Get a workspace by ID (excludes soft deleted)
    async fn get_workspace(&self, input: GetWorkspaceRepoInput)
        -> DomainResult<Option<Workspace>>;

    /// Update a workspace
    async fn update_workspace(&self, input: UpdateWorkspaceRepoInput) -> DomainResult<Workspace>;

    /// Soft delete a workspace
    async fn delete_workspace(&self, input: DeleteWorkspaceRepoInput) -> DomainResult<()>;

    /// List all active workspaces for an organization (excludes soft deleted)
    async fn list_workspaces(
        &self,
        input: ListWorkspacesRepoInput,
    ) -> DomainResult<Vec<Workspace>>;
}
