use crate::domain::{CreateDeviceInput, Device, GetDeviceInput, ListDevicesInput};
use chrono::{DateTime, Utc};
use ponix_proto_prost::end_device::v1::{
    CreateEndDeviceRequest, EndDevice, GetEndDeviceRequest, ListEndDevicesRequest,
};
use prost_types::Timestamp;

/// Convert protobuf Timestamp to chrono DateTime
#[allow(dead_code)]
fn timestamp_to_datetime(ts: Option<Timestamp>) -> Option<DateTime<Utc>> {
    ts.and_then(|t| DateTime::from_timestamp(t.seconds, t.nanos as u32))
}

/// Convert chrono DateTime to protobuf Timestamp
fn datetime_to_timestamp(dt: Option<DateTime<Utc>>) -> Option<Timestamp> {
    dt.map(|d| Timestamp {
        seconds: d.timestamp(),
        nanos: d.timestamp_subsec_nanos() as i32,
    })
}

/// Convert protobuf CreateEndDeviceRequest to domain CreateDeviceInput
/// Note: device_id is generated by the domain service, not provided in the request
pub fn to_create_device_input(req: CreateEndDeviceRequest) -> CreateDeviceInput {
    CreateDeviceInput {
        organization_id: req.organization_id,
        name: req.name,
        payload_conversion: req.payload_conversion,
    }
}

/// Convert domain Device to protobuf EndDevice
pub fn to_proto_device(device: Device) -> EndDevice {
    EndDevice {
        device_id: device.device_id,
        organization_id: device.organization_id,
        name: device.name,
        payload_conversion: device.payload_conversion,
        created_at: datetime_to_timestamp(device.created_at),
        updated_at: datetime_to_timestamp(device.updated_at),
    }
}

/// Convert protobuf GetEndDeviceRequest to domain GetDeviceInput
pub fn to_get_device_input(req: GetEndDeviceRequest) -> GetDeviceInput {
    GetDeviceInput {
        device_id: req.device_id,
        organization_id: req.organization_id,
    }
}

/// Convert protobuf ListEndDevicesRequest to domain ListDevicesInput
pub fn to_list_devices_input(req: ListEndDevicesRequest) -> ListDevicesInput {
    ListDevicesInput {
        organization_id: req.organization_id,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;

    #[test]
    fn test_create_request_to_domain() {
        let req = CreateEndDeviceRequest {
            organization_id: "org-456".to_string(),
            name: "Test Device".to_string(),
            payload_conversion: "test conversion".to_string(),
        };

        let input = to_create_device_input(req);

        // device_id is generated by domain service, not in CreateDeviceInput
        assert_eq!(input.organization_id, "org-456");
        assert_eq!(input.name, "Test Device");
        assert_eq!(input.payload_conversion, "test conversion");
    }

    #[test]
    fn test_domain_device_to_proto() {
        let now = Utc::now();
        let device = Device {
            device_id: "device-123".to_string(),
            organization_id: "org-456".to_string(),
            name: "Test Device".to_string(),
            payload_conversion: "test conversion".to_string(),
            created_at: Some(now),
            updated_at: Some(now),
        };

        let proto = to_proto_device(device);

        assert_eq!(proto.device_id, "device-123");
        assert_eq!(proto.organization_id, "org-456");
        assert_eq!(proto.name, "Test Device");
        assert_eq!(proto.payload_conversion, "test conversion");
        assert!(proto.created_at.is_some());
        assert!(proto.updated_at.is_some());
    }
}
